# Generated by Django 5.1.1 on 2024-11-18 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('magyar', 'magyar')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Rövid termék leírás')),
                ('price', models.IntegerField()),
                ('image', models.CharField(default='None', max_length=100)),
                ('stock', models.IntegerField()),
                ('categoryId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CreateProductQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Rövid termék leírás')),
                ('price', models.IntegerField()),
                ('image', models.CharField(default='None', max_length=100)),
                ('stock', models.IntegerField()),
                ('categoryId', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
