# Generated by Django 5.1.1 on 2024-11-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createproductqueue',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='createproductqueue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=15, null=True),
        ),
    ]
