# Generated by Django 5.1.1 on 2024-12-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(max_length=10)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
