# Generated by Django 5.1.1 on 2024-12-01 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 8, 12, 5, 12, 434427, tzinfo=datetime.timezone.utc)),
        ),
    ]
