# Generated by Django 5.1.1 on 2024-12-04 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_engine', '0007_alter_customsession_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 13, 42, 15, 170779, tzinfo=datetime.timezone.utc)),
        ),
    ]
