# Generated by Django 5.1.1 on 2024-11-18 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemManager', '0001_initial'),
        ('main', '0002_cartmodel_cartitems_delete_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='itemId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemManager.product'),
        ),
    ]
