# Generated by Django 5.1.1 on 2024-11-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoryId',
            field=models.IntegerField(),
        ),
    ]
