# Generated by Django 5.1.1 on 2024-11-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_product_image'),
        ('main', '0003_delete_category_alter_cartitems_itemid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
