"""
Django settings for sajt project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from telnetlib import AUTHENTICATION, LOGOUT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_DIR = os.path.join(BASE_DIR, 'main')
STATIC_ROOT = os.path.join(BASE_DIR, 'static_files')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oo5^ivnr1h6cx@=iq1pq9d%(y@qh+oa&n1^a5lz#bvhsm%tfv9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
SITE_ID = 2
CART_SESSION_ID = 'cart'
INSTALLED_APPS = [
    'django.contrib.admin'
    ,'django.contrib.auth'
    ,'django.contrib.contenttypes'
    ,'django.contrib.sessions'
    ,'django.contrib.messages'
    ,'django.contrib.staticfiles'
    # own app
    ,'main'    
    ,'accounts'
    ,'django.contrib.sites'
    ,'allauth'
    ,'allauth.account'
    ,'allauth.socialaccount'
    ,'allauth.socialaccount.providers.google'
    ,'itemManager'
    ,'K_localization_framework'
    ,'session_engine'
]
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}
SOCIALACCOUNT_LOGIN_ON_GET=True
SOCIALACCOUNT_LOGOUT_ON_GET=True
AUTH_USER_MODEL = "accounts.CustomUser"
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Default
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware'
    ,'django.contrib.sessions.middleware.SessionMiddleware'
    ,'django.middleware.common.CommonMiddleware'
    ,'django.middleware.csrf.CsrfViewMiddleware'
    ,'django.contrib.auth.middleware.AuthenticationMiddleware'
    ,'django.contrib.messages.middleware.MessageMiddleware'
    ,'django.middleware.clickjacking.XFrameOptionsMiddleware'
    ,'allauth.account.middleware.AccountMiddleware'
    #,'K_localization_framework.middleware.LanguageMiddleware'
    , 'session_engine.middleware.SessionEngineMiddleware'
    , 'session_engine.middleware.CustomSessionAuthenticationMiddleware'
]

Q_CLUSTER = {
    'name': 'Django Q',
    'workers': 4,
    'timeout': 60,
    'recycle': 500,
    'retry': 300,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default'
}

ROOT_URLCONF = 'sajt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Frontend'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sajt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Zurich'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfiles'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend'
)

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'emails')
EMAIL_HOST = 'live.smtp.mailtrap.io'
EMAIL_HOST_USER = 'api'
EMAIL_HOST_PASSWORD = '9214d61f4dcafa6acaab3b65dcdebd00'
EMAIL_PORT = '587'


CONTACTS = {
    "CONTACT_PHONE": '36 6 666 6969'
    ,"CONTACT_EMAIL_SUPPORT": 'infoSajtosok@gmail.hu'
    ,"CONTACT_ADDRESS": 'Sajtkedvelő utca 1'
    ,"CONTACT_CITY": '1234 Budapest'
    ,"CONTACT_COUNTRY": 'Sajt Country'
    ,"SALES_MANAGER_NAME": 'Sales Manager'
    ,"SALES_MANAGER_PHONE": '+36 30 12-345-6789'
    ,"SALES_MANAGER_EMAIL": 'sajtfanatikus.sales@example.hu'
    ,"FACEBOOK":"https://facebook.com/endpoint123"
    ,"INSTAGRAM":"https://instagram.com/endpoint123"
    ,"TWITTER":"https://twitter.com/endpoint123"
}


