# Generated by Django 5.1.1 on 2024-11-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_google_customuser_last_login_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_name_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_google',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(choices=[('member', 'member'), ('admin', 'admin'), ('developper', 'developper'), ('owner', 'owner')], default='member', max_length=20),
        ),
    ]
