# Generated by Django 5.1.1 on 2024-11-30 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_is_google_passwordresettoken'),
        ('itemManager', '0002_createproductqueue_reason_createproductqueue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('Bács-Kiskun', 'Bács-Kiskun'), ('Baranya', 'Baranya'), ('Békés', 'Békés'), ('Borsod-Abaúj-Zemplén', 'Borsod-Abaúj-Zemplén'), ('Fejér', 'Fejér'), ('Győr-Moson-Sopron', 'Győr-Moson-Sopron'), ('Hajdú-Bihar', 'Hajdú-Bihar'), ('Heves', 'Heves'), ('Jász-Nagykun-Szolnok', 'Jász-Nagykun-Szolnok'), ('Komárom-Esztergom', 'Komárom-Esztergom'), ('Nógrád', 'Nógrád'), ('Pest', 'Pest'), ('Somogy', 'Somogy'), ('Szabolcs-Szatmár-Bereg', 'Szabolcs-Szatmár-Bereg'), ('Tolna', 'Tolna'), ('Vas', 'Vas'), ('Veszprém', 'Veszprém'), ('Zala', 'Zala'), ('Veszprém', 'Veszprém')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemManager.category')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemManager.product')),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('feedback_stars', models.IntegerField()),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemManager.product')),
            ],
        ),
        migrations.CreateModel(
            name='saved_Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street1', models.CharField(max_length=100)),
                ('street2', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zipcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
            ],
        ),
    ]
