# Generated by Django 5.1.1 on 2024-11-30 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.saved_shipment'),
        ),
    ]
