# Generated by Django 5.1.1 on 2024-12-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_is_authenticated_customuser_is_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_auth',
            new_name='is_authenticated',
        ),
    ]
